lotok/urls.py
from django.conf.urls import url

from lotok.views import *

urlpatterns = [
    url(r'^$', index),
    url(r'category/(?P<name>\w+)', category, name='category'),
    url(r'product/(?P<name>\w+)', product, name='product'),
]

tstp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lotok/', include('lotok.urls')),
]

lotok/models.py
import hashlib
from django.db import models
from django.utils.translation import ugettext_lazy as _

from mptt.models import TreeForeignKey, MPTTModel

from hranilishe.filesystem import *


class Category(MPTTModel):
    name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    parent = TreeForeignKey('self', null=True, blank=True,
                                        related_name='children', db_index=True)

    class Meta:
        verbose_name = u'category'
        verbose_name_plural = u'category'
        ordering = ('name', )

    class MPTTMeta:
        order_insertion_by = ['name']

    def __unicode__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category)
    name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    is_hidden = models.BooleanField(_(u'Do not show this product'), default=False)
    registered = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _(u'machine')
        verbose_name_plural = _(u'machines')
        ordering = ('name', )

    def __unicode__(self):
        return u'{}: {}'.format(self.name, self.dimension)


class Property(models.Model):
    product = models.ForeignKey(Product)
    key = models.CharField(verbose_name=_(u'title'), max_length=64)
    value = models.CharField(verbose_name=_(u'value'), max_length=128)

    class Meta:
        verbose_name = _(u'Property')
        verbose_name_plural = _(u'Properties')
        ordering = ('key',)

    def __unicode__(self):
        return self.key


class Media(models.Model):
    filename = models.CharField(max_length=255, blank=True, null=True)
    resource = models.FileField(_(u'model'), max_length=256,
                                upload_to=upload_by_hash,
                                storage=HashedFileSystemStorage())
    size = models.PositiveIntegerField(default=0, help_text=_(u'The size of the uploaded detail.'))
    is_compressed = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    registered = models.DateTimeField(auto_now_add=True)

    # служебное поле, используется для организации хранения файлов,
    # см. функцию upload_by_hash выше
    md5sum = models.CharField(max_length=36)

    def save(self, *args, **kwargs):
        u"""Вычисляет MD5 от содержимого файла и записывает его в поле модели.
        При сохранении функция upload_by_hash берёт вычисленный хэш из модели и
        записывает на файловую систему с помощью HashedFileSystemStorage.
        """
        if not self.pk:  # сохранение нового объекта
            md5 = hashlib.md5()
            for chunk in self.resource.chunks():
                md5.update(chunk)
            self.md5sum = md5.hexdigest()
            self.size = self.resource.file.size
        super(Media, self).save(*args, **kwargs)

lotok/views.py
from django.shortcuts import render, get_object_or_404

from lotok.models import Category, Product


def index(request):
    return render(request, 'tstapp/index.html', {
        'categories': Category.objects.all()
    })


def category(request, name):
    return render(request, 'tstapp/category.html', {
        'category': get_object_or_404(Category, name=name)
    })


def product(request, name):
    return render(request, 'tstapp/product.html', {
        'product': get_object_or_404(Product, name=name)
    })

templates/tstapp/category.html
{% extends 'tstapp/index.html' %}
{% block content %}
    <p>Category info</p>
    <p>{{ category.name }}</p>
    <ul>
        {% for product in category.product_set.all %}
            <li><a href="{% url 'product' product.name %}">{{ product.name }}</a></li>
        {% empty %}
            <li>Category have not products</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/tstapp/index.html
{% load mptt_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf8">
    <title>Title</title>
</head>
<body>
{% block content %}
    <ul>
        {% recursetree categories %}
            <li>
                <a href="{% url 'category' name=node.name %}">{{ node.name }}</a>
                {% if not node.is_leaf_node %}
                    <ul class="children">
                        {{ children }}
                    </ul>
                {% endif %}
            </li>
        {% endrecursetree %}
    </ul>
{% endblock %}
</body>
</html>

templates/tstapp/product.html
{% extends 'tstapp/index.html' %}
{% block content %}
    <p>Product info</p>
    <p>{{ product.name }}</p>
    <ul>
    {% for property in product.property_set.all %}
        <li>Title: {{ property.key }}, value: {{ property.value }}</li>
    {% empty %}
        <li>Product have not properties</li>
    {% endfor %}
    </ul>
{% endblock %}